[package]
name = "nexus-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
nexus-core = { path = "../../crates/nexus-core" }
nexus-platform = { path = "../../crates/nexus-platform" }
nexus-process = { path = "../../crates/nexus-process" }
nexus-resource = { path = "../../crates/nexus-resource" }
nexus-storage = { path = "../../crates/nexus-storage" }
